services:
    express-app:
        image: maxiviper117/express-app-test:latest
        container_name: express-app
        ports:
            - "3000:3000"
        restart: unless-stopped

    caddy:
        image: caddy:latest
        container_name: caddy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/caddy/Caddyfile:/etc/caddy/Caddyfile
        restart: unless-stopped
